#!/usr/bin/python
import sys
import os
import subprocess

if (len(sys.argv) < 4):
	print('Usage: ./kdress <vmlinuz> <vmlinux> <System.map>\n')
	sys.exit(-1)

subprocess.call(['./kunpress', sys.argv[1], sys.argv[2]])
subprocess.call(['./build_ksyms', sys.argv[2], '/tmp/.vmlinux.abc', sys.argv[3]])
subprocess.call(['/bin/mv', '/tmp/.vmlinux.abc', sys.argv[2]])


